import Head from "next/head";
import { Inter } from "@next/font/google";
import { Box, Heading } from "@chakra-ui/react";
import Hero from "@/components/hero";
import Loading from "@/components/loading";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Pixelate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Box>
        <Hero />
      </Box>
    </>
  );
}
